### ISSUE TITLE
Improve variable names

### ISSUE THREAD

**Issue by szepeviktor** [crwlrsoft/crawler#113]
Currently there are ~300 lines with names like key, value, data.
Please consider using informative variable names.
[_source_](https://github.com/szepeviktor/uninformative-words)

```php
// For example
protected function setDomain(string $value, bool $viaAttribute = false): void {}
protected function setDomain(string $domainName, bool $viaAttribute = false): void {}
```

**Comment by otsch** [comment]
Those occurrences don't have to be bad per se. For example some occurrences are even dictated by PSR interfaces, like in the [`CacheInterface` of PSR-16](https://github.com/php-fig/simple-cache/blob/master/src/CacheInterface.php), which absolutely make sense. As I don't really see a big "issue" here, I'll close this. Send a PR if you like to improve some particular variable names.
