### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by MathiasReker** [crwlrsoft/crawler#77]
Hello

Cool project.

Would it be possible to lower the minimum PHP version to PHP 8?

**Comment by otsch** [comment]
Hello Mathias,
first of all thank you! 🙂🙏🏻
I hope you understand that this is not really an option. The library uses PHP 8.1 features like enums for example. So I'd have to refactor it to work on PHP 8.0 which is already in the "security fixes only" stage and will be end of life by the end of this year.
If you really like the library and it would be very important for you to run it on PHP 8.0, you could create a fork and refactor it. If you have any questions I can maybe also assist you.
