### ISSUE TITLE
Extracting <script> tags

### ISSUE THREAD

**Issue by dimitardimitrov2** [crwlrsoft/crawler#78]
Hi, what would be the best way to extract all <script> tags with their `src` attribute?
I've been trying the code below, looks like working fine, but getting empty strings as `src` and deprecation warnings:
`Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/XXXX/Projects/php-scraper/vendor/crwlr/crawler/src/Steps/Html/DomQuery.php on line 255`

```php
use Crwlr\Crawler\Exceptions\UnknownLoaderKeyException;
use Crwlr\Crawler\HttpCrawler;
use Crwlr\Crawler\Steps\Dom;
use Crwlr\Crawler\Steps\Html;
use Crwlr\Crawler\Steps\Loading\Http;

try {
    $domain = 'https://XXXX.com/';

    $crawler = HttpCrawler::make()
        ->withBotUserAgent('Agent')
        ->input($domain)
        ->addStep(Http::get())
        ->addStep(
            Html::root()
                ->extract([
                    'scripts' => Dom::cssSelector('script')->attribute('src'),
                ])
        );
} catch (UnknownLoaderKeyException $e) {
}

foreach ($crawler->run() as $result) {
    var_dump($result->toArray());
}
```

**Comment by otsch** [comment]
Hi, I guess the page you're loading also contains `<script>` tags without a src attribute. You can adapt the CSS selector to get only `<script>` nodes with a `src` attribute, like:

```php
Html::root()
    ->extract([
        'scripts' => Dom::cssSelector('script[src]')->attribute('src'),
    ])
```

Hope it helps.

**Comment by dimitardimitrov2** [comment]
Thanks, worked like a charm!
