### ISSUE TITLE
Paginating links with JavaScript href

### ISSUE THREAD

**Issue by pjdevries** [crwlrsoft/crawler#89]
Hi Christian,

Thanks for making this useful library available to mere mortals like me.

I have read the docs and found the `paginate()` method, but it does not work in my situation. The links to the next page are not ordinary links with an ordinary url in the `href`, but some JavaScript that triggers a page refresh with the new data. The website is not quite a SPA, but this particular page behaves somewhat like one. Is there any way to make this work?

**Comment by otsch** [comment]
Hi Pieter-Jan,
thank you for the kind words 🙂🙏🏻
From your description I think it sounds definitely solvable, but I think best would be if you can share the actual URL of that site. If you don't want to share it publicly you can also DM me on twitter ([@chrolear](https://twitter.com/chrolear) or [@crwlrsoft](https://twitter.com/crwlrsoft)) or send it via the [contact form on crwlr.software](https://www.crwlr.software/contact). I'll try to help you and maybe we can even find some reusable, generic way to tackle such pagination, to add it to the library as well.

**Comment by pjdevries** [comment]
Hi Otsch,

Being somewhat of a paranoid dinosaur, I don´t use Twitter or similar platforms. So it's going to be your contact form :)
